"""Initial migration.

Revision ID: 036fe4e2e0d2
Revises: 
Create Date: 2020-11-22 22:23:57.295524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036fe4e2e0d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('word_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=1000), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=False),
    sa.Column('flexion', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=1000), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammatical_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Enum('singular', 'plural'), nullable=True),
    sa.Column('word_form_id', sa.Integer(), nullable=False),
    sa.Column('nominative_id', sa.Integer(), nullable=True),
    sa.Column('genitive_id', sa.Integer(), nullable=True),
    sa.Column('dative_id', sa.Integer(), nullable=True),
    sa.Column('accusative_id', sa.Integer(), nullable=True),
    sa.Column('instrumental_id', sa.Integer(), nullable=True),
    sa.Column('locative_id', sa.Integer(), nullable=True),
    sa.Column('vocative_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accusative_id'], ['word_form.id'], ),
    sa.ForeignKeyConstraint(['dative_id'], ['word_form.id'], ),
    sa.ForeignKeyConstraint(['genitive_id'], ['word_form.id'], ),
    sa.ForeignKeyConstraint(['instrumental_id'], ['word_form.id'], ),
    sa.ForeignKeyConstraint(['locative_id'], ['word_form.id'], ),
    sa.ForeignKeyConstraint(['nominative_id'], ['word_form.id'], ),
    sa.ForeignKeyConstraint(['vocative_id'], ['word_form.id'], ),
    sa.ForeignKeyConstraint(['word_form_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accusative_id'),
    sa.UniqueConstraint('dative_id'),
    sa.UniqueConstraint('genitive_id'),
    sa.UniqueConstraint('instrumental_id'),
    sa.UniqueConstraint('locative_id'),
    sa.UniqueConstraint('nominative_id'),
    sa.UniqueConstraint('vocative_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grammatical_case')
    op.drop_table('word')
    op.drop_table('source')
    op.drop_table('word_form')
    op.drop_table('user')
    # ### end Alembic commands ###
